build: Update phan to fix crash on PHP 8.4
```
PHP Deprecated:  Constant ASSERT_ACTIVE is deprecated in /stillalive/vendor/phan/phan/src/Phan/Bootstrap.php on line 199
PHP Deprecated: Function assert_options() is deprecated since 8.3 in /stillalive/vendor/phan/phan/src/Phan/Bootstrap.php on line 206

/stillalive/vendor/phan/phan/src/Phan/Issue.php:5934 [8192] Phan\Issue::__invoke(): Implicitly marking parameter $suggestion as nullable is deprecated, the explicit nullable type must be used instead
More details:
ERROR: Error: Class "Phan\Issue" not found
in /stillalive/vendor/phan/phan/src/Phan/Config.php:366
at stillalive/vendor/bin/phan:119
Script phan … returned with error code 1
```

Bug: T395164
Change-Id: Ifbff46d42e5c8387889ef3ff5c631a5d1a55589f